DROP TABLE EMP_BASE;
DROP TABLE AUTHORITY;
DROP TABLE ROLE;
DROP SEQUENCE SEQ_EMP_BASE;

CREATE SEQUENCE SEQ_EMP_BASE;
CREATE TABLE EMP_BASE 
( EMP_ID VARCHAR2(100) PRIMARY KEY,
  PASSWORD VARCHAR2(100) NOT NULL,
  COMPANY_CD VARCHAR2(10) NOT NULL,
  EMP_NO VARCHAR2(10) NOT NULL,
  EMP_NAME VARCHAR2(10) NOT NULL,
  CTZ_NO VARCHAR2(100),
  EMAIL VARCHAR2(100),
  EMP_KIND_CD VARCHAR2(10) NOT NULL,
  HIRE_CD VARCHAR2(10) NOT NULL,
  IN_OFF_YN CHAR(1) NOT NULL,
  GENDER_CD CHAR(1) NOT NULL,
  BIRTH_YMD DATE NOT NULL,
  POS_GRD_CD VARCHAR2(10),
  POS_CD VARCHAR2(10),
  YEAR_CD VARCHAR2(10),
  ORG_CD VARCHAR2(10),
  DUTY_CD VARCHAR2(10),
  JOB_CD VARCHAR2(10),
  PAY_ORG_CD VARCHAR2(10),
  HIRE_YMD DATE,
  RETIRE_YMD DATE,
  RETIRE_TYPE_CD VARCHAR2(10),
  CAREER_NUM NUMBER,
  FILE_PATH_ID VARCHAR2(100),
  MOD_USER_ID NUMBER,
  MOD_DATE DATE,
  TZ_CD  VARCHAR2(10), 
  TZ_DATE DATE
);

COMMENT ON COLUMN EMP_BASE.EMP_ID IS '사원 아이디';
COMMENT ON COLUMN EMP_BASE.PWD IS '비밀번호';
COMMENT ON COLUMN EMP_BASE.COMPANY_CD IS '회사 코드';
COMMENT ON COLUMN EMP_BASE.EMP_NAME IS '사번';
COMMENT ON COLUMN EMP_BASE.CTZ_NO IS '주민번호';
COMMENT ON COLUMN EMP_BASE.EMP_KIND_CD IS '직원 구분 코드';
COMMENT ON COLUMN EMP_BASE.HIRE_CD IS '입사 구분 코드';
COMMENT ON COLUMN EMP_BASE.IN_OFF_YN IS '재직 여부';
COMMENT ON COLUMN EMP_BASE.GENDER_CD IS '성별';
COMMENT ON COLUMN EMP_BASE.BIRTH_YMD IS '생년월일';
COMMENT ON COLUMN EMP_BASE.POS_GRD_CD IS '직급 코드';
COMMENT ON COLUMN EMP_BASE.POS_CD IS '직위 코드';
COMMENT ON COLUMN EMP_BASE.YEAR_CD IS '호봉 코드';
COMMENT ON COLUMN EMP_BASE.ORG_CD IS '부서 코드';
COMMENT ON COLUMN EMP_BASE.DUTY_CD IS '직책 코드';
COMMENT ON COLUMN EMP_BASE.JOB_CD IS '직무 코드';
COMMENT ON COLUMN EMP_BASE.PAY_ORG_CD IS '급여 코드';
COMMENT ON COLUMN EMP_BASE.HIRE_YMD IS '입사일';
COMMENT ON COLUMN EMP_BASE.RETIRE_YMD IS '퇴사일';
COMMENT ON COLUMN EMP_BASE.RETIRE_TYPE_CD IS '퇴사 구분 코드';
COMMENT ON COLUMN EMP_BASE.CAREER_NUM IS '경력 인정 개월 수';
COMMENT ON COLUMN EMP_BASE.FILE_PATH_ID IS '파일 패스 ID';
COMMENT ON COLUMN EMP_BASE.MOD_USER_ID IS '수정자';
COMMENT ON COLUMN EMP_BASE.MOD_DATE IS '수정일';
COMMENT ON COLUMN EMP_BASE.TZ_CD IS '타임존코드';
COMMENT ON COLUMN EMP_BASE.TZ_DATE IS '타임존일시';



CREATE TABLE AUTHORITY (
  AUTHORITY_CODE NUMBER NOT NULL,
  AUTHORITY_NAME NVARCHAR2(30) NOT NULL,
  AUTHORITY_DESC NVARCHAR2(255) NOT NULL
 );

COMMENT ON COLUMN AUTHORITY.AUTHORITY_CODE IS '권한코드';
COMMENT ON COLUMN AUTHORITY.AUTHORITY_NAME IS '권한 명';
COMMENT ON COLUMN AUTHORITY.AUTHORITY_DESC IS '권한 설명';

 CREATE TABLE ROLE (
  AUTHORITY_CODE NUMBER NOT NULL,
  EMPLOYEE_NO NUMBER NULL
 );

COMMENT ON COLUMN ROLE.AUTHORITY_CODE IS '권한코드';
COMMENT ON COLUMN ROLE.EMPLOYEE_NO IS '직원번호';
