CREATE USER C##HR_SYSTEM IDENTIFIED BY HR_SYSTEM;                           
GRANT CONNECT, RESOURCE TO C##HR_SYSTEM;  

GRANT CONNECT, RESOURCE, CREATE VIEW TO C##HR_SYSTEM;
ALTER USER C##HR_SYSTEM DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; -- TABLESPACE È®º¸
ALTER USER C##HR_SYSTEM QUOTA 1024M ON SYSTEM;   