INSERT INTO AUTHORITY (AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC)
VALUES (1, 'ROLE_EMPLOYEE', '사원');

INSERT INTO AUTHORITY (AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC)
VALUES (2, 'ROLE_ADMIN_SEC', '보안 담당자');

INSERT INTO AUTHORITY (AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC)
VALUES (3, 'ROLE_ADMIN_HR', '인사 담당자');

INSERT INTO AUTHORITY (AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC)
VALUES (4, 'ROLE_ADMIN_FNC', '재정 담당자');

INSERT INTO AUTHORITY (AUTHORITY_CODE, AUTHORITY_NAME, AUTHORITY_DESC)
VALUES (5, 'ROLE_BOSS', '사장');